# Generated by Django 5.1.6 on 2025-03-02 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laundry', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LaundryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='laundryrequest',
            name='item_name',
        ),
        migrations.RemoveField(
            model_name='laundryrequest',
            name='quantity',
        ),
        migrations.CreateModel(
            name='LaundryRequestItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laundry.laundryitem')),
                ('laundry_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laundry.laundryrequest')),
            ],
        ),
        migrations.AddField(
            model_name='laundryrequest',
            name='items',
            field=models.ManyToManyField(through='laundry.LaundryRequestItem', to='laundry.laundryitem'),
        ),
    ]
