# Generated by Django 5.0.2 on 2025-04-04 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laundry', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedback',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='feedback',
            name='viewed',
            field=models.BooleanField(default=False),
        ),
    ]
