# Generated by Django 5.1.6 on 2025-03-02 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laundry', '0002_laundryitem_remove_laundryrequest_item_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laundryrequest',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Recieved', 'Recieved'), ('In Progress', 'In Progress'), ('Completed', 'Completed')], default='Pending', max_length=20),
        ),
    ]
