# Generated by Django 5.0.2 on 2025-04-04 19:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laundry', '0002_alter_feedback_options_feedback_viewed'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='laundry_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='laundry.laundryrequest'),
        ),
        migrations.AlterUniqueTogether(
            name='feedback',
            unique_together={('user', 'laundry_request')},
        ),
    ]
