# Generated by Django 5.1.6 on 2025-03-02 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laundry', '0004_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='unique_number',
        ),
    ]
