# Generated by Django 5.1.6 on 2025-03-02 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laundry', '0006_userprofile_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='laundryrequest',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
